name:                vformat-time
version:             0.1.0.0
synopsis:            Extend vformat to time datatypes
github:              versioncloud/vformat-time
category:            Text, Format, Time
license:             BSD3
author:              "Jorah Gao"
maintainer:          "jorah@version.cloud"
copyright:           "Copyright (c) 2020 Version Cloud"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see http://hackage.haskell.org/package/vformat-time

dependencies:
- base >= 4.7 && < 5
- time >= 1.4 && < 2.0
- vformat >= 0.12 && < 1.0

library:
  source-dirs: src

tests:
  vformat-time-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vformat-time
